#!/usr/bin/env python3

#
# gwcheck
# Copyright (c) 2021, Frederic Cambus
# https://github.com/fcambus/gwcheck
#
# Created: 2011-11-04
# Last Updated: 2021-11-04
#
# gwcheck is released under the BSD 2-Clause license.
# See LICENSE file for details.
#
# SPDX-License-Identifier: BSD-2-Clause
#

import sys
from elftools.elf.elffile import ELFFile


def main():
    with open(sys.argv[1], "rb") as f:
        for section in ELFFile(f).iter_sections():
            if section["sh_type"] == "SHT_PROGBITS":
                if section.name.startswith(".gnu.warning"):
                    print(section.name + ":")
                    print("\t" + section.data().decode("utf-8").rstrip("\0"))


if __name__ == "__main__":
    main()
