#!/usr/bin/env python3

#
# gwcheck
# Copyright (c) 2021, Frederic Cambus
# https://github.com/fcambus/gwcheck
#
# Created: 2011-11-04
# Last Updated: 2021-11-05
#
# gwcheck is released under the BSD 2-Clause license.
# See LICENSE file for details.
#
# SPDX-License-Identifier: BSD-2-Clause
#

import getopt
import textwrap
import sys
from elftools.elf.elffile import ELFFile
from elftools.common.exceptions import ELFError


def usage():
    usage = """\
            gwcheck [-hv] object

            The options are as follows:

            	-h	Display usage.
            	-v	Display version."""

    print(textwrap.dedent(usage))


def main():
    # Verify that gwcheck receives at least one argument
    try:
        sys.argv[1]
    except IndexError:
        usage()
        sys.exit(0)
    else:
        input = sys.argv[1]

    # Process command line arguments
    try:
        options, args = getopt.getopt(sys.argv[1:], "hv")
    except getopt.GetoptError as err:
        print(err)
        sys.exit(1)

    for option, arg in options:
        if option == "-h":
            usage()
            sys.exit(0)
        if option == "-v":
            print("gwcheck 1.0.0")
            sys.exit(0)

    # Process ELF object
    with open(input, "rb") as object:
        try:
            for section in ELFFile(object).iter_sections():
                if section["sh_type"] == "SHT_PROGBITS":
                    if section.name.startswith(".gnu.warning"):
                        print(section.name + ":")
                        print("\t" + section.data().decode("utf-8").rstrip("\0"))
        except ELFError as ex:
            sys.stderr.write("Error: %s\n" % ex)
            sys.exit(1)


if __name__ == "__main__":
    main()
