.\"
.\" Copyright (c) 2021, Frederic Cambus
.\" https://github.com/fcambus/gwcheck
.\"
.\" gwcheck is released under the BSD 2-Clause license.
.\" See LICENSE file for details.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd $Mdocdate: November 4 2021 $
.Dt GWCHECK 1
.Os
.Sh NAME
.Nm gwcheck
.Nd Check .gnu.warning.* sections in ELF object files
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Ar object
.Sh DESCRIPTION
.Nm
is a tool to check .gnu.warning.* sections in ELF object files
and display their content.
.Pp
Support for emitting linker warnings when using a symbol for which
a .gnu.warning.symbol section exists is implemented in GNU linkers
(ld and gold), but currently not in LLVM's LLD linker.
.Pp
The options are as follows:
.Bl -tag -width 10n
.It Fl h
Display usage.
.It Fl v
Display version.
.El
.Sh AUTHORS
.Nm
was written by
.An Frederic Cambus .
